export const gameCharacters = {
  1: [
    { name: "Ryu", img: "https://placehold.co/300x400?text=Ryu" },
    { name: "Ken", img: "https://placehold.co/300x400?text=Ken" },
    { name: "Chun-Li", img: "https://placehold.co/300x400?text=Chun-Li" },
    { name: "Guile", img: "https://placehold.co/300x400?text=Guile" },
    { name: "Blanka", img: "https://placehold.co/300x400?text=Blanka" },
    { name: "Bison", img: "https://placehold.co/300x400?text=Bison" },
    { name: "Retsu", img: "https://placehold.co/300x400?text=Retsu" },
    { name: "Geki", img: "https://placehold.co/300x400?text=Geki" },
    { name: "Joe", img: "https://placehold.co/300x400?text=Joe" },
    { name: "Mike", img: "https://placehold.co/300x400?text=Mike" },
    { name: "Lee", img: "https://placehold.co/300x400?text=Lee" },
    { name: "Gen", img: "https://placehold.co/300x400?text=Gen" },
    { name: "Birdie", img: "https://placehold.co/300x400?text=Birdie" },
    { name: "Eagle", img: "https://placehold.co/300x400?text=Eagle  " },
    { name: "Adon", img: "https://placehold.co/300x400?text=Adon" },
    { name: "Sagat", img: "https://placehold.co/300x400?text=Sagat" },
    { name: "Dhalsim", img: "https://placehold.co/300x400?text=Dhalsim" },
    { name: "Zangief", img: "https://placehold.co/300x400?text=Zangief" },
    { name: "Balrog", img: "https://placehold.co/300x400?text=Balrog" },
    { name: "Vega", img: "https://placehold.co/300x400?text=Vega" },
    { name: "Cammy", img: "https://placehold.co/300x400?text=Cammy" },
  ],
  2: [
    { name: "Jin", img: "https://placehold.co/300x400?text=Jin" },
    { name: "Kazuya", img: "https://placehold.co/300x400?text=Kazuya" },
    { name: "Paul", img: "https://placehold.co/300x400?text=Paul" },
    { name: "Alex", img: "https://placehold.co/300x400?text=Alex" },
    { name: "Angel", img: "https://placehold.co/300x400?text=Angel" },
    { name: "Anna", img: "https://placehold.co/300x400?text=Anna" },
    { name: "Asuka", img: "https://placehold.co/300x400?text=Asuka" },
    { name: "Baek", img: "https://placehold.co/300x400?text=Baek" },
    { name: "Bruce", img: "https://placehold.co/300x400?text=Brube" },
    { name: "Bryan", img: "https://placehold.co/300x400?text=Bryan" },
    { name: "Christie", img: "https://placehold.co/300x400?text=Christie" },
    { name: "Craig", img: "https://placehold.co/300x400?text=Craig" },
    {
      name: "Dr.Bosconovitch",
      img: "https://placehold.co/300x400?text=Dr.Bosconovitch",
    },
    { name: "Eddie", img: "https://placehold.co/300x400?text=Eddie" },
    { name: "Feng", img: "https://placehold.co/300x400?text=Feng" },
    { name: "Forrest", img: "https://placehold.co/300x400?text=Forrest" },
    { name: "Ganryu", img: "https://placehold.co/300x400?text=Ganryu" },
    { name: "Heihachi", img: "https://placehold.co/300x400?text=Heihachi" },
    { name: "Hwoarang", img: "https://placehold.co/300x400?text=Hwoarang" },
    { name: "Jack", img: "https://placehold.co/300x400?text=Jack" },
    { name: "Jane", img: "https://placehold.co/300x400?text=Jane" },
    { name: "Jinpachi", img: "https://placehold.co/300x400?text=Jinpachi" },
    { name: "Julia", img: "https://placehold.co/300x400?text=Julia" },
    { name: "Jun", img: "https://placehold.co/300x400?text=Jun" },
    { name: "Kuma", img: "https://placehold.co/300x400?text=Kuma" },
    { name: "Lee", img: "https://placehold.co/300x400?text=Lee" },
    { name: "Lei", img: "https://placehold.co/300x400?text=Lei" },
    { name: "Ling", img: "https://placehold.co/300x400?text=Ling" },
    { name: "Marshall", img: "https://placehold.co/300x400?text=Marshall" },
    { name: "Michelle", img: "https://placehold.co/300x400?text=Michelle" },
  ],
  3: [
    { name: "Scorpion", img: "https://placehold.co/300x400?text=Scorpion" },
    { name: "Sub-Zero", img: "https://placehold.co/300x400?text=Sub-Zero" },
    { name: "Raiden", img: "https://placehold.co/300x400?text=Raiden" },
    {
      name: "Bo'Rai Cho",
      img: "https://placehold.co/300x400?text=Bo' Rai Cho",
    },
    { name: "Cassie", img: "https://placehold.co/300x400?text=Cassie" },
    { name: "D'Vorah", img: "https://placehold.co/300x400?text=D'Vorah" },
    { name: "Ermac", img: "https://placehold.co/300x400?text=Ermac" },
    { name: "Erron", img: "https://placehold.co/300x400?text=Erron" },
    { name: "Ferra", img: "https://placehold.co/300x400?text=Ferra" },
    { name: "Goro", img: "https://placehold.co/300x400?text=Goro" },
    { name: "Jacqui", img: "https://placehold.co/300x400?text=Jacqui" },
    { name: "Jason", img: "https://placehold.co/300x400?text=Jason" },
    { name: "Jax", img: "https://placehold.co/300x400?text=Jax" },
    { name: "Johnny Cage", img: "https://placehold.co/300x400?text=Johnny" },
    { name: "Kano", img: "https://placehold.co/300x400?text=Kano" },
    { name: "Kenshi", img: "https://placehold.co/300x400?text=Kenshi" },
    { name: "Kitana", img: "https://placehold.co/300x400?text=Kitana" },
    { name: "Kotal Khan", img: "https://placehold.co/300x400?text=Kotal Khan" },
    { name: "Kung Jin", img: "https://placehold.co/300x400?text=Kung Jin" },
    { name: "Kung Lao", img: "https://placehold.co/300x400?text=Kung Lao" },
    {
      name: "Leatherface",
      img: "https://placehold.co/300x400?text=Leatherface",
    },
    { name: "Liu Kang", img: "https://placehold.co/300x400?text=Liu Kang" },
    { name: "Mileena", img: "https://placehold.co/300x400?text=Mileena" },
    { name: "Predator", img: "https://placehold.co/300x400?text=Predator" },
    { name: "Quain Chi", img: "https://placehold.co/300x400?text=Quain Chi" },
    { name: "Reptile", img: "https://placehold.co/300x400?text=Reptile" },
    { name: "Shinnok", img: "https://placehold.co/300x400?text=SHinnok" },
    { name: "Takeda", img: "https://placehold.co/300x400?text=Takeda" },
    { name: "Tanya", img: "https://placehold.co/300x400?text=Tanya" },
    { name: "Tremor", img: "https://placehold.co/300x400?text=Tremor" },
    { name: "Triborg", img: "https://placehold.co/300x400?text=Triborg" },
  ],
  4: [
    { name: "Cervantes", img: "https://placehold.co/300x400?text=Cervantes" },
    { name: "Mitsurugi", img: "https://placehold.co/300x400?text=Mitsurugi" },
    { name: "Taki", img: "https://placehold.co/300x400?text=Taki" },
    { name: "Astaroth", img: "https://placehold.co/300x400?text=Astaroth" },
    { name: "Sophitia", img: "https://placehold.co/300x400?text=Sophitia" },
    { name: "Kilik", img: "https://placehold.co/300x400?text=Kilik" },
    { name: "Xianghua", img: "https://placehold.co/300x400?text=Xianghua" },
    { name: "Voldo", img: "https://placehold.co/300x400?text=Voldo" },
    { name: "Nightmare", img: "https://placehold.co/300x400?text=Nightmare" },
    { name: "Tira", img: "https://placehold.co/300x400?text=Tira" },
    { name: "Ivy", img: "https://placehold.co/300x400?text=Ivy" },
    { name: "Zasalamel", img: "https://placehold.co/300x400?text=Zasalamel" },
    { name: "Setsuka", img: "https://placehold.co/300x400?text=Setsuka" },
    { name: "Yun-Seong", img: "https://placehold.co/300x400?text=Yun-Seong" },
    { name: "Algol", img: "https://placehold.co/300x400?text=Algol" },
    { name: "Patroklos", img: "https://placehold.co/300x400?text=Patroklos" },
    { name: "Pyrrha", img: "https://placehold.co/300x400?text=Pyrrha" },
    { name: "Viola", img: "https://placehold.co/300x400?text=Viola" },
    { name: "Groh", img: "https://placehold.co/300x400?text=Groh" },
    { name: "Azwel", img: "https://placehold.co/300x400?text=Azwel" },
  ],
  5: [
    { name: "Goku", img: "https://placehold.co/300x400?text=Goku" },
    { name: "Vegeta", img: "https://placehold.co/300x400?text=Vegeta" },
    { name: "Gohan", img: "https://placehold.co/300x400?text=Gohan" },
    { name: "Piccolo", img: "https://placehold.co/300x400?text=Piccolo" },
    { name: "Krillin", img: "https://placehold.co/300x400?text=Krillin" },
    { name: "Android 16", img: "https://placehold.co/300x400?text=Android+16" },
    { name: "Android 17", img: "https://placehold.co/300x400?text=Android+17" },
    { name: "Android 18", img: "https://placehold.co/300x400?text=Android+18" },
    { name: "21 Android", img: "https://placehold.co/300x400?text=21+Android" },
    { name: "Beerus", img: "https://placehold.co/300x400?text=Beerus" },
    { name: "Cell", img: "https://placehold.co/300x400?text=Cell" },
    { name: "Frieza", img: "https://placehold.co/300x400?text=Frieza" },
    { name: "Majin Buu", img: "https://placehold.co/300x400?text=Majin+Buu" },
    { name: "Kid Buu", img: "https://placehold.co/300x400?text=Kid+Buu" },
    { name: "Nappa", img: "https://placehold.co/300x400?text=Nappa" },
    { name: "Trunks", img: "https://placehold.co/300x400?text=Trunks" },
    { name: "Yamcha", img: "https://placehold.co/300x400?text=Yamcha" },
    { name: "Chiaotzu", img: "https://placehold.co/300x400?text=Chiaotzu" },
    {
      name: "Tien Shinhan",
      img: "https://placehold.co/300x400?text=Tien+Shinhan",
    },
    { name: "Gotenks", img: "https://placehold.co/300x400?text=Gotenks" },
    { name: "Hit", img: "https://placehold.co/300x400?text=Hit" },
  ],
  6: [
    { name: "Aquaman", img: "https://placehold.co/300x400?text=Aquaman" },
    { name: "Atrocitus", img: "https://placehold.co/300x400?text=Atrocitus" },
    { name: "Bane", img: "https://placehold.co/300x400?text=Bane" },
    { name: "Batman", img: "https://placehold.co/300x400?text=Batman" },
    { name: "Black Adam", img: "https://placehold.co/300x400?text=Black+Adam" },
    {
      name: "Black Canary",
      img: "https://placehold.co/300x400?text=Black+Canary",
    },
    {
      name: "Blue Beetle",
      img: "https://placehold.co/300x400?text=Blue+Beetle",
    },
    { name: "Brainiac", img: "https://placehold.co/300x400?text=Brainiac" },
    {
      name: "Captain Cold",
      img: "https://placehold.co/300x400?text=Captain+Cold",
    },
    { name: "Catwoman", img: "https://placehold.co/300x400?text=Catwoman" },
    { name: "Cheetah", img: "https://placehold.co/300x400?text=Cheetah" },
    { name: "Cyborg", img: "https://placehold.co/300x400?text=Cyborg" },
    { name: "Darkseid", img: "https://placehold.co/300x400?text=Darkseid" },
    { name: "Deadshot", img: "https://placehold.co/300x400?text=Deadshot" },
    {
      name: "Doctor Fate",
      img: "https://placehold.co/300x400?text=Doctor+Fate",
    },
    { name: "Firestorm", img: "https://placehold.co/300x400?text=Firestorm" },
    { name: "The Flash", img: "https://placehold.co/300x400?text=The+Flash" },
    {
      name: "Gorilla Grodd",
      img: "https://placehold.co/300x400?text=Gorilla+Grodd",
    },
    {
      name: "Green Arrow",
      img: "https://placehold.co/300x400?text=Green+Arrow",
    },
    {
      name: "Green Lantern",
      img: "https://placehold.co/300x400?text=Green+Lantern",
    },
    {
      name: "Harley Quinn",
      img: "https://placehold.co/300x400?text=Harley+Quinn",
    },
    { name: "Joker", img: "https://placehold.co/300x400?text=Joker" },
    { name: "Poison Ivy", img: "https://placehold.co/300x400?text=Poison+Ivy" },
    { name: "Red Hood", img: "https://placehold.co/300x400?text=Red+Hood" },
    {
      name: "Robin (Damian Wayne)",
      img: "https://placehold.co/300x400?text=Robin+(Damian+Wayne)",
    },
    { name: "Scarecrow", img: "https://placehold.co/300x400?text=Scarecrow" },
    { name: "Supergirl", img: "https://placehold.co/300x400?text=Supergirl" },
    { name: "Superman", img: "https://placehold.co/300x400?text=Superman" },
    {
      name: "Swamp Thing",
      img: "https://placehold.co/300x400?text=Swamp Thing",
    },
    {
      name: "Wonder Woman",
      img: "https://placehold.co/300x400?text=Wonder Woman",
    },
    {
      name: "Black Manta",
      img: "https://placehold.co/300x400?text=Black Manta",
    },
    { name: "Raiden", img: "https://placehold.co/300x400?text=Raiden" },
    { name: "HellBoy", img: "https://placehold.co/300x400?text=Hellboy" },
    {
      name: "Enchantress",
      img: "https://placehold.co/300x400?text=Enchantress",
    },
    { name: "Sub-Zero", img: "https://placehold.co/300x400?text=Sub-Zero" },
    { name: "Stafire", img: "https://placehold.co/300x400?text=Stafire" },
    {
      name: "Teenage Mutant Ninja Turtles",
      img: "https://placehold.co/300x400?text=Teenage Mutant Ninja Turtles",
    },
  ],
};
