export const gameCharacters = {
  1: [
    { name: "Ryu", img: "https://placehold.co/300x400?text=Ryu", description:"Descrição teste" },
    { name: "Ken", img: "https://placehold.co/300x400?text=Ken" },
    { name: "Chun-Li", img: "https://placehold.co/300x400?text=Chun-Li" },
    { name: "Guile", img: "https://placehold.co/300x400?text=Guile" },
    { name: "Blanka", img: "https://placehold.co/300x400?text=Blanka" },
    { name: "Bison", img: "https://placehold.co/300x400?text=Bison" },
    { name: "Retsu", img: "https://placehold.co/300x400?text=Retsu" },
    { name: "Geki", img: "https://placehold.co/300x400?text=Geki" },
    { name: "Joe", img: "https://placehold.co/300x400?text=Joe" },
    { name: "Mike", img: "https://placehold.co/300x400?text=Mike" },
    { name: "Lee", img: "https://placehold.co/300x400?text=Lee" },
    { name: "Gen", img: "https://placehold.co/300x400?text=Gen" },
    { name: "Birdie", img: "https://placehold.co/300x400?text=Birdie" },
    { name: "Eagle", img: "https://placehold.co/300x400?text=Eagle  " },
    { name: "Adon", img: "https://placehold.co/300x400?text=Adon" },
    { name: "Sagat", img: "https://placehold.co/300x400?text=Sagat" },
    { name: "Dhalsim", img: "https://placehold.co/300x400?text=Dhalsim" },
    { name: "Zangief", img: "https://placehold.co/300x400?text=Zangief" },
    { name: "Balrog", img: "https://placehold.co/300x400?text=Balrog" },
    { name: "Vega", img: "https://placehold.co/300x400?text=Vega" },
    { name: "Cammy", img: "https://placehold.co/300x400?text=Cammy" },
  ],
  2: [
    { name: "Jin", img: "https://placehold.co/300x400?text=Jin" },
    { name: "Kazuya", img: "https://placehold.co/300x400?text=Kazuya" },
    { name: "Paul", img: "https://placehold.co/300x400?text=Paul" },
    { name: "Alex", img: "https://placehold.co/300x400?text=Alex" },
    { name: "Angel", img: "https://placehold.co/300x400?text=Angel" },
    { name: "Anna", img: "https://placehold.co/300x400?text=Anna" },
    { name: "Asuka", img: "https://placehold.co/300x400?text=Asuka" },
    { name: "Baek", img: "https://placehold.co/300x400?text=Baek" },
    { name: "Bruce", img: "https://placehold.co/300x400?text=Brube" },
    { name: "Bryan", img: "https://placehold.co/300x400?text=Bryan" },
    { name: "Christie", img: "https://placehold.co/300x400?text=Christie" },
    { name: "Craig", img: "https://placehold.co/300x400?text=Craig" },
    {
      name: "Dr.Bosconovitch",
      img: "https://placehold.co/300x400?text=Dr.Bosconovitch",
    },
    { name: "Eddie", img: "https://placehold.co/300x400?text=Eddie" },
    { name: "Feng", img: "https://placehold.co/300x400?text=Feng" },
    { name: "Forrest", img: "https://placehold.co/300x400?text=Forrest" },
    { name: "Ganryu", img: "https://placehold.co/300x400?text=Ganryu" },
    { name: "Heihachi", img: "https://placehold.co/300x400?text=Heihachi" },
    { name: "Hwoarang", img: "https://placehold.co/300x400?text=Hwoarang" },
    { name: "Jack", img: "https://placehold.co/300x400?text=Jack" },
    { name: "Jane", img: "https://placehold.co/300x400?text=Jane" },
    { name: "Jinpachi", img: "https://placehold.co/300x400?text=Jinpachi" },
    { name: "Julia", img: "https://placehold.co/300x400?text=Julia" },
    { name: "Jun", img: "https://placehold.co/300x400?text=Jun" },
    { name: "Kuma", img: "https://placehold.co/300x400?text=Kuma" },
    { name: "Lee", img: "https://placehold.co/300x400?text=Lee" },
    { name: "Lei", img: "https://placehold.co/300x400?text=Lei" },
    { name: "Ling", img: "https://placehold.co/300x400?text=Ling" },
    { name: "Marshall", img: "https://placehold.co/300x400?text=Marshall" },
    { name: "Michelle", img: "https://placehold.co/300x400?text=Michelle" },
  ],
  3: [
    { name: "Scorpion", img: "https://placehold.co/300x400?text=Scorpion" },
    { name: "Sub-Zero", img: "https://placehold.co/300x400?text=Sub-Zero" },
    { name: "Raiden", img: "https://placehold.co/300x400?text=Raiden" },
    {
      name: "Bo'Rai Cho",
      img: "https://placehold.co/300x400?text=Bo' Rai Cho",
    },
    { name: "Cassie", img: "https://placehold.co/300x400?text=Cassie" },
    { name: "D'Vorah", img: "https://placehold.co/300x400?text=D'Vorah" },
    { name: "Ermac", img: "https://placehold.co/300x400?text=Ermac" },
    { name: "Erron", img: "https://placehold.co/300x400?text=Erron" },
    { name: "Ferra", img: "https://placehold.co/300x400?text=Ferra" },
    { name: "Goro", img: "https://placehold.co/300x400?text=Goro" },
    { name: "Jacqui", img: "https://placehold.co/300x400?text=Jacqui" },
    { name: "Jason", img: "https://placehold.co/300x400?text=Jason" },
    { name: "Jax", img: "https://placehold.co/300x400?text=Jax" },
    { name: "Johnny Cage", img: "https://placehold.co/300x400?text=Johnny" },
    { name: "Kano", img: "https://placehold.co/300x400?text=Kano" },
    { name: "Kenshi", img: "https://placehold.co/300x400?text=Kenshi" },
    { name: "Kitana", img: "https://placehold.co/300x400?text=Kitana" },
    { name: "Kotal Khan", img: "https://placehold.co/300x400?text=Kotal Khan" },
    { name: "Kung Jin", img: "https://placehold.co/300x400?text=Kung Jin" },
    { name: "Kung Lao", img: "https://placehold.co/300x400?text=Kung Lao" },
    {
      name: "Leatherface",
      img: "https://placehold.co/300x400?text=Leatherface",
    },
    { name: "Liu Kang", img: "https://placehold.co/300x400?text=Liu Kang" },
    { name: "Mileena", img: "https://placehold.co/300x400?text=Mileena" },
    { name: "Predator", img: "https://placehold.co/300x400?text=Predator" },
    { name: "Quain Chi", img: "https://placehold.co/300x400?text=Quain Chi" },
    { name: "Reptile", img: "https://placehold.co/300x400?text=Reptile" },
    { name: "Shinnok", img: "https://placehold.co/300x400?text=SHinnok" },
    { name: "Takeda", img: "https://placehold.co/300x400?text=Takeda" },
    { name: "Tanya", img: "https://placehold.co/300x400?text=Tanya" },
    { name: "Tremor", img: "https://placehold.co/300x400?text=Tremor" },
    { name: "Triborg", img: "https://placehold.co/300x400?text=Triborg" },
  ],
  4: [
    { name: "Cervantes", img: "https://placehold.co/300x400?text=Cervantes" },
    { name: "Mitsurugi", img: "https://placehold.co/300x400?text=Mitsurugi" },
    { name: "Taki", img: "https://placehold.co/300x400?text=Taki" },
    { name: "Astaroth", img: "https://placehold.co/300x400?text=Astaroth" },
    { name: "Sophitia", img: "https://placehold.co/300x400?text=Sophitia" },
    { name: "Kilik", img: "https://placehold.co/300x400?text=Kilik" },
    { name: "Xianghua", img: "https://placehold.co/300x400?text=Xianghua" },
    { name: "Voldo", img: "https://placehold.co/300x400?text=Voldo" },
    { name: "Nightmare", img: "https://placehold.co/300x400?text=Nightmare" },
    { name: "Tira", img: "https://placehold.co/300x400?text=Tira" },
    { name: "Ivy", img: "https://placehold.co/300x400?text=Ivy" },
    { name: "Zasalamel", img: "https://placehold.co/300x400?text=Zasalamel" },
    { name: "Setsuka", img: "https://placehold.co/300x400?text=Setsuka" },
    { name: "Yun-Seong", img: "https://placehold.co/300x400?text=Yun-Seong" },
    { name: "Algol", img: "https://placehold.co/300x400?text=Algol" },
    { name: "Patroklos", img: "https://placehold.co/300x400?text=Patroklos" },
    { name: "Pyrrha", img: "https://placehold.co/300x400?text=Pyrrha" },
    { name: "Viola", img: "https://placehold.co/300x400?text=Viola" },
    { name: "Groh", img: "https://placehold.co/300x400?text=Groh" },
    { name: "Azwel", img: "https://placehold.co/300x400?text=Azwel" },
  ],
  5: [
    { name: "Goku", img: "https://placehold.co/300x400?text=Goku" },
    { name: "Vegeta", img: "https://placehold.co/300x400?text=Vegeta" },
    { name: "Gohan", img: "https://placehold.co/300x400?text=Gohan" },
    { name: "Piccolo", img: "https://placehold.co/300x400?text=Piccolo" },
    { name: "Krillin", img: "https://placehold.co/300x400?text=Krillin" },
    { name: "Android 16", img: "https://placehold.co/300x400?text=Android+16" },
    { name: "Android 17", img: "https://placehold.co/300x400?text=Android+17" },
    { name: "Android 18", img: "https://placehold.co/300x400?text=Android+18" },
    { name: "21 Android", img: "https://placehold.co/300x400?text=21+Android" },
    { name: "Beerus", img: "https://placehold.co/300x400?text=Beerus" },
    { name: "Cell", img: "https://placehold.co/300x400?text=Cell" },
    { name: "Frieza", img: "https://placehold.co/300x400?text=Frieza" },
    { name: "Majin Buu", img: "https://placehold.co/300x400?text=Majin+Buu" },
    { name: "Kid Buu", img: "https://placehold.co/300x400?text=Kid+Buu" },
    { name: "Nappa", img: "https://placehold.co/300x400?text=Nappa" },
    { name: "Trunks", img: "https://placehold.co/300x400?text=Trunks" },
    { name: "Yamcha", img: "https://placehold.co/300x400?text=Yamcha" },
    { name: "Chiaotzu", img: "https://placehold.co/300x400?text=Chiaotzu" },
    {
      name: "Tien Shinhan",
      img: "https://placehold.co/300x400?text=Tien+Shinhan",
    },
    { name: "Gotenks", img: "https://placehold.co/300x400?text=Gotenks" },
    { name: "Hit", img: "https://placehold.co/300x400?text=Hit" },
  ],
  6: [
    { name: "Aquaman", img: "https://placehold.co/300x400?text=Aquaman" },
    { name: "Atrocitus", img: "https://placehold.co/300x400?text=Atrocitus" },
    { name: "Bane", img: "https://placehold.co/300x400?text=Bane" },
    { name: "Batman", img: "https://placehold.co/300x400?text=Batman" },
    { name: "Black Adam", img: "https://placehold.co/300x400?text=Black+Adam" },
    {
      name: "Black Canary",
      img: "https://placehold.co/300x400?text=Black+Canary",
    },
    {
      name: "Blue Beetle",
      img: "https://placehold.co/300x400?text=Blue+Beetle",
    },
    { name: "Brainiac", img: "https://placehold.co/300x400?text=Brainiac" },
    {
      name: "Captain Cold",
      img: "https://placehold.co/300x400?text=Captain+Cold",
    },
    { name: "Catwoman", img: "https://placehold.co/300x400?text=Catwoman" },
    { name: "Cheetah", img: "https://placehold.co/300x400?text=Cheetah" },
    { name: "Cyborg", img: "https://placehold.co/300x400?text=Cyborg" },
    { name: "Darkseid", img: "https://placehold.co/300x400?text=Darkseid" },
    { name: "Deadshot", img: "https://placehold.co/300x400?text=Deadshot" },
    {
      name: "Doctor Fate",
      img: "https://placehold.co/300x400?text=Doctor+Fate",
    },
    { name: "Firestorm", img: "https://placehold.co/300x400?text=Firestorm" },
    { name: "The Flash", img: "https://placehold.co/300x400?text=The+Flash" },
    {
      name: "Gorilla Grodd",
      img: "https://placehold.co/300x400?text=Gorilla+Grodd",
    },
    {
      name: "Green Arrow",
      img: "https://placehold.co/300x400?text=Green+Arrow",
    },
    {
      name: "Green Lantern",
      img: "https://placehold.co/300x400?text=Green+Lantern",
    },
    {
      name: "Harley Quinn",
      img: "https://placehold.co/300x400?text=Harley+Quinn",
    },
    { name: "Joker", img: "https://placehold.co/300x400?text=Joker" },
    { name: "Poison Ivy", img: "https://placehold.co/300x400?text=Poison+Ivy" },
    { name: "Red Hood", img: "https://placehold.co/300x400?text=Red+Hood" },
    {
      name: "Robin (Damian Wayne)",
      img: "https://placehold.co/300x400?text=Robin+(Damian+Wayne)",
    },
    { name: "Scarecrow", img: "https://placehold.co/300x400?text=Scarecrow" },
    { name: "Supergirl", img: "https://placehold.co/300x400?text=Supergirl" },
    { name: "Superman", img: "https://placehold.co/300x400?text=Superman" },
    {
      name: "Swamp Thing",
      img: "https://placehold.co/300x400?text=Swamp Thing",
    },
    {
      name: "Wonder Woman",
      img: "https://placehold.co/300x400?text=Wonder Woman",
    },
    {
      name: "Black Manta",
      img: "https://placehold.co/300x400?text=Black Manta",
    },
    { name: "Raiden", img: "https://placehold.co/300x400?text=Raiden" },
    { name: "HellBoy", img: "https://placehold.co/300x400?text=Hellboy" },
    {
      name: "Enchantress",
      img: "https://placehold.co/300x400?text=Enchantress",
    },
    { name: "Sub-Zero", img: "https://placehold.co/300x400?text=Sub-Zero" },
    { name: "Stafire", img: "https://placehold.co/300x400?text=Stafire" },
    {
      name: "Teenage Mutant Ninja Turtles",
      img: "https://placehold.co/300x400?text=Teenage Mutant Ninja Turtles",
    },
  ],
  7: [
    { name: "Sol Badguy", img: "https://placehold.co/300x400?text=Sol+Badguy" },
    { name: "Ky Kiske", img: "https://placehold.co/300x400?text=Ky+Kiske" },
    { name: "May", img: "https://placehold.co/300x400?text=May" },
    { name: "Zato-1", img: "https://placehold.co/300x400?text=Zato-1" },
    { name: "Millia Rage", img: "https://placehold.co/300x400?text=Millia+Rage" },
    { name: "Chipp Zanuff", img: "https://placehold.co/300x400?text=Chipp+Zanuff" },
    { name: "Potemkin", img: "https://placehold.co/300x400?text=Potemkin" },
    { name: "Faust", img: "https://placehold.co/300x400?text=Faust" },
    { name: "Ramlethal Valentine", img: "https://placehold.co/300x400?text=Ramlethal+Valentine" },
    { name: "Nagoriyuki", img: "https://placehold.co/300x400?text=Nagoriyuki" },
  ],
  8: [
    { name: "Ragna the Bloodedge", img: "https://placehold.co/300x400?text=Ragna+the+Bloodedge" },
    { name: "Jin Kisaragi", img: "https://placehold.co/300x400?text=Jin+Kisaragi" },
    { name: "Noel Vermillion", img: "https://placehold.co/300x400?text=Noel+Vermillion" },
    { name: "Rachel Alucard", img: "https://placehold.co/300x400?text=Rachel+Alucard" },
    { name: "Hazama", img: "https://placehold.co/300x400?text=Hazama" },
    { name: "Makoto Nanaya", img: "https://placehold.co/300x400?text=Makoto+Nanaya" },
    { name: "Tager", img: "https://placehold.co/300x400?text=Tager" },
    { name: "Lambda-11", img: "https://placehold.co/300x400?text=Lambda-11" },
    { name: "Es", img: "https://placehold.co/300x400?text=Es" },
    { name: "Yang Xiao Long", img: "https://placehold.co/300x400?text=Yang+Xiao+Long" },
  ],
  9: [
    { name: "Kyo Kusanagi", img: "https://placehold.co/300x400?text=Kyo+Kusanagi" },
    { name: "Iori Yagami", img: "https://placehold.co/300x400?text=Iori+Yagami" },
    { name: "Mai Shiranui", img: "https://placehold.co/300x400?text=Mai+Shiranui" },
    { name: "Terry Bogard", img: "https://placehold.co/300x400?text=Terry+Bogard" },
    { name: "Ryo Sakazaki", img: "https://placehold.co/300x400?text=Ryo+Sakazaki" },
    { name: "Leona Heidern", img: "https://placehold.co/300x400?text=Leona+Heidern" },
    { name: "Athena Asamiya", img: "https://placehold.co/300x400?text=Athena+Asamiya" },
    { name: "Kim Kaphwan", img: "https://placehold.co/300x400?text=Kim+Kaphwan" },
    { name: "Shermie", img: "https://placehold.co/300x400?text=Shermie" },
    { name: "Yashiro Nanakase", img: "https://placehold.co/300x400?text=Yashiro+Nanakase" },
  ],
  10: [
    { name: "Kasumi", img: "https://placehold.co/300x400?text=Kasumi" },
    { name: "Ayane", img: "https://placehold.co/300x400?text=Ayane" },
    { name: "Ryu Hayabusa", img: "https://placehold.co/300x400?text=Ryu+Hayabusa" },
    { name: "Hitomi", img: "https://placehold.co/300x400?text=Hitomi" },
    { name: "Helena Douglas", img: "https://placehold.co/300x400?text=Helena+Douglas" },
    { name: "Hayate", img: "https://placehold.co/300x400?text=Hayate" },
    { name: "Kokoro", img: "https://placehold.co/300x400?text=Kokoro" },
    { name: "Marie Rose", img: "https://placehold.co/300x400?text=Marie+Rose" },
    { name: "Nyotengu", img: "https://placehold.co/300x400?text=Nyotengu" },
    { name: "Rig", img: "https://placehold.co/300x400?text=Rig" },
  ],
  11: [
    { name: "Filia", img: "https://placehold.co/300x400?text=Filia" },
    { name: "Cerebella", img: "https://placehold.co/300x400?text=Cerebella" },
    { name: "Peacock", img: "https://placehold.co/300x400?text=Peacock" },
    { name: "Parasoul", img: "https://placehold.co/300x400?text=Parasoul" },
    { name: "Ms. Fortune", img: "https://placehold.co/300x400?text=Ms.+Fortune" },
    { name: "Painwheel", img: "https://placehold.co/300x400?text=Painwheel" },
    { name: "Valentine", img: "https://placehold.co/300x400?text=Valentine" },
    { name: "Double", img: "https://placehold.co/300x400?text=Double" },
    { name: "Squigly", img: "https://placehold.co/300x400?text=Squigly" },
    { name: "Big Band", img: "https://placehold.co/300x400?text=Big+Band" },
  ],
  12: [
    { name: "Shiki Tohno", img: "https://placehold.co/300x400?text=Shiki+Tohno" },
    { name: "Arcueid Brunestud", img: "https://placehold.co/300x400?text=Arcueid+Brunestud" },
    { name: "Ciel", img: "https://placehold.co/300x400?text=Ciel" },
    { name: "Akiha Tohno", img: "https://placehold.co/300x400?text=Akiha+Tohno" },
    { name: "Hisui", img: "https://placehold.co/300x400?text=Hisui" },
    { name: "Kohaku", img: "https://placehold.co/300x400?text=Kohaku" },
    { name: "Noel", img: "https://placehold.co/300x400?text=Noel" },
    { name: "Vlov Arkhangel", img: "https://placehold.co/300x400?text=Vlov+Arkhangel" },
    { name: "Red Arcueid", img: "https://placehold.co/300x400?text=Red+Arcueid" },
    { name: "Saber", img: "https://placehold.co/300x400?text=Saber" },
  ],
};
export const jogosDeLuta = [
  {
    id: 1,
    nome: "Street Fighter 20",
    desenvolvedora: "Capcom",
    lancamento: "2023",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    imagem: "street-fighter-20.jpg",
  },
  {
    id: 2,
    nome: "Tekken 5",
    desenvolvedora: "Bandai Namco",
    lancamento: "2005",
    plataformas: ["PS2", "Arcade"],
    imagem: "tekken-5.jpg",
  },
  {
    id: 3,
    nome: "Mortal Kombat X",
    desenvolvedora: "NetherRealm Studios",
    lancamento: "2015",
    plataformas: ["PS4", "Xbox One", "PC"],
    imagem: "mortal-kombat-x.jpg",
  },
  {
    id: 4,
    nome: "Soul Calibur VI",
    desenvolvedora: "Bandai Namco",
    lancamento: "2018",
    plataformas: ["PS4", "Xbox One", "PC"],
    imagem: "soul-calibur-vi.jpg",
  },
  {
    id: 5,
    nome: "Dragon Ball FighterZ",
    desenvolvedora: "Arc System Works",
    lancamento: "2018",
    plataformas: ["PS4", "Xbox One", "Switch", "PC"],
    imagem: "dragon-ball-fighterz.jpg",
  },
  {
    id: 6,
    nome: "Injustice 2",
    desenvolvedora: "NetherRealm Studios",
    lancamento: "2017",
    plataformas: ["PS4", "Xbox One", "PC"],
    imagem: "injustice-2.jpg",
  },

  // NOVOS JOGOS ADICIONADOS
  {
    id: 7,
    nome: "Guilty Gear Strive",
    desenvolvedora: "Arc System Works",
    lancamento: "2021",
    plataformas: ["PS4", "PS5", "PC"],
    imagem: "guilty-gear-strive.jpg",
  },
  {
    id: 8,
    nome: "BlazBlue: Cross Tag Battle",
    desenvolvedora: "Arc System Works",
    lancamento: "2018",
    plataformas: ["PS4", "Switch", "PC"],
    imagem: "blazblue-cross-tag-battle.jpg",
  },
  {
    id: 9,
    nome: "The King of Fighters XV",
    desenvolvedora: "SNK",
    lancamento: "2022",
    plataformas: ["PS4", "PS5", "Xbox Series X", "PC"],
    imagem: "kof-xv.jpg",
  },
  {
    id: 10,
    nome: "Dead or Alive 6",
    desenvolvedora: "Team Ninja",
    lancamento: "2019",
    plataformas: ["PS4", "Xbox One", "PC"],
    imagem: "dead-or-alive-6.jpg",
  },
  {
    id: 11,
    nome: "Skullgirls 2nd Encore",
    desenvolvedora: "Lab Zero Games",
    lancamento: "2015",
    plataformas: ["PS4", "Switch", "PC"],
    imagem: "skullgirls-2nd-encore.jpg",
  },
  {
    id: 12,
    nome: "Melty Blood: Type Lumina",
    desenvolvedora: "French-Bread",
    lancamento: "2021",
    plataformas: ["PS4", "Switch", "Xbox One", "PC"],
    imagem: "melty-blood-type-lumina.jpg",
  },
];
